### ISSUE TITLE
Address NbMM with synonyms

### ISSUE THREAD

**Issue by dwolt** [ongroup/mvmason#38]
Set up new Netbuilder accounts with NB MM mm and Mm as synonyms for NbMM.

**Comment by dwolt** [comment]
I think this one has been completed. Let me know if not.

**Comment by GrantHart** [comment]
Completed


Grant Hart
Chief Technology Officer

[cid:image002.jpg@01D29CB4.43F63160]

T

|

+27 86 177 6765

M

|

+27 83 646 8888

E

|

grant.hart@prosolgrp.com<mailto:grant.hart@prosolgrp.com>

W

|

www.prosolgrp.co<http://www.prosolgrp.co.za>m
